[versions]
agp = "8.12.0-alpha03"
composeMarkdown = "0.3.4"
coreSplashscreen = "1.0.1"
hiltNavigationCompose = "1.2.0"
kotlin = '2.0.21'
kotlin-ksp-version = '2.0.21-1.0.27'
coreKtx = "1.16.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
lifecycleRuntimeKtx = "2.9.2"
activityCompose = "1.10.1"
composeBom = "2025.07.00"
datastore = "1.1.7"
loggingInterceptor = "4.12.0"
material = "1.12.0"
navigationCompose = "2.9.3"
okhttp = "4.12.0"
protobuf-javalite = "4.31.1"
protobuf-plugin = "0.9.5"
moshi-version = '1.15.2'
retrofit = "3.0.0"
retrofit2-version = '3.0.0'
hilt-version = '2.57'
hilt-jetpack-version = '1.2.0'
symbolProcessingApi = "2.1.10-1.0.31"
timber-version = '5.0.1'
image-glide-version = '4.16.0'
image-glide-okhttp-version = '4.16.0'
image-glide-compose = '1.0.0-beta01'
lottie-compose-version = '6.6.7'
playServicesLocation = "21.3.0"


[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreen" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigationCompose" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
compose-markdown = { module = "com.github.jeziellago:compose-markdown", version.ref = "composeMarkdown" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-datastore = { module = "androidx.datastore:datastore", version.ref = "datastore" }
androidx-datastore-core = { module = "androidx.datastore:datastore-core", version.ref = "datastore" }
androidx-datastore-preferences-core = { group = "androidx.datastore", name = "datastore-preferences-core", version.ref = "datastore" }
androidx-datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "loggingInterceptor" }
material = { module = "com.google.android.material:material", version.ref = "material" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
protobuf-javalite = { module = "com.google.protobuf:protobuf-javalite", version.ref = "protobuf-javalite" }
moshi-kotlin = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshi-version" }
moshi-ksp = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "moshi-version" }
moshi-adapters = { module = "com.squareup.moshi:moshi-adapters", version.ref = "moshi-version" }
moshi-converter = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "retrofit2-version" }
hilt-android-core = { module = "com.google.dagger:hilt-android", version.ref = "hilt-version" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt-version" }
hilt-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "hilt-jetpack-version" }
hilt-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "hilt-version" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
symbol-processing-api = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "symbolProcessingApi" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber-version" }
glide-core = { module = "com.github.bumptech.glide:glide", version.ref = "image-glide-version" }
glide-okhttp = { module = "com.github.bumptech.glide:okhttp3-integration", version.ref = "image-glide-okhttp-version" }
glide-compose = { module = "com.github.bumptech.glide:compose", version.ref = "image-glide-compose" }
lottie-compose = { module = "com.airbnb.android:lottie-compose", version.ref = "lottie-compose-version" }
play-services-location = { group = "com.google.android.gms", name = "play-services-location", version.ref = "playServicesLocation" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
protobuf = { id = "com.google.protobuf", version.ref = "protobuf-plugin" }
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt-version" }
kotlin-ksp = { id = "com.google.devtools.ksp", version.ref = "kotlin-ksp-version" }

